export const historicalFigures = [
    {
        name: "Mustafa Kemal Atatürk",
        title: "founder and first president of the Republic of Turkey",
        achievements: "establishing a modern, secular Turkish state",
        audienceName: "the reader",
        tone: "authoritative yet approachable",
        areasOfInfluence: "nation-building, modernization, education, and secularism",
    },
    {
        name: "Albert Einstein",
        title: "theoretical physicist",
        achievements: "developing the theory of relativity",
        audienceName: "the curious learner",
        tone: "intellectual and thought-provoking",
        areasOfInfluence: "physics, mathematics, philosophy",
    },
    {
        name: "Cleopatra",
        title: "Queen of Egypt",
        achievements: "her political acumen and leadership in ancient Egypt",
        audienceName: "an admirer of ancient history",
        tone: "charismatic and wise",
        areasOfInfluence: "leadership, diplomacy, and ancient Egyptian culture",
    },
    {
        name: "Leonardo da Vinci",
        title: "polymath and Renaissance artist",
        achievements: "masterpieces such as the Mona Lisa and contributions to scientific and engineering knowledge",
        audienceName: "an aspiring artist or scientist",
        tone: "insightful and creative",
        areasOfInfluence: "art, science, anatomy, engineering",
    },
    {
        name: "Julius Caesar",
        title: "Roman general and statesman",
        achievements: "leading the expansion of the Roman Empire",
        audienceName: "a student of military history",
        tone: "strategic and confident",
        areasOfInfluence: "military strategy, politics, leadership",
    },
    {
        name: "Mahatma Gandhi",
        title: "leader of the Indian independence movement",
        achievements: "championing nonviolent resistance",
        audienceName: "a peace advocate or activist",
        tone: "calm and wise",
        areasOfInfluence: "nonviolence, social justice, independence movements",
    },
    {
        name: "Marie Curie",
        title: "pioneering physicist and chemist",
        achievements: "discovering radioactivity and winning two Nobel Prizes",
        audienceName: "an aspiring scientist",
        tone: "intellectual and inspirational",
        areasOfInfluence: "physics, chemistry, scientific research",
    },
    {
        name: "Martin Luther King Jr.",
        title: "civil rights leader",
        achievements: "leading the American civil rights movement",
        audienceName: "someone passionate about social justice",
        tone: "motivational and visionary",
        areasOfInfluence: "civil rights, social equality, nonviolent protest",
    },
    {
        name: "Isaac Newton",
        title: "mathematician and physicist",
        achievements: "formulating the laws of motion and universal gravitation",
        audienceName: "a science enthusiast",
        tone: "analytical and precise",
        areasOfInfluence: "physics, mathematics, astronomy",
    },
    {
        name: "Queen Elizabeth I",
        title: "Queen of England",
        achievements: "establishing England as a major European power and supporting the arts",
        audienceName: "a history enthusiast",
        tone: "wise and regal",
        areasOfInfluence: "leadership, diplomacy, arts patronage",
    },
    {
        name: "Alexander the Great",
        title: "King of Macedonia and conqueror",
        achievements: "creating one of the largest empires in the ancient world",
        audienceName: "a military history enthusiast",
        tone: "ambitious and charismatic",
        areasOfInfluence: "military strategy, leadership, cultural integration",
    },
    {
        name: "Napoleon Bonaparte",
        title: "French military leader and emperor",
        achievements: "leading France and expanding the empire across Europe",
        audienceName: "an admirer of strategic leadership",
        tone: "determined and strategic",
        areasOfInfluence: "military strategy, politics, leadership",
    },
    {
        name: "Winston Churchill",
        title: "British Prime Minister during WWII",
        achievements: "leading Britain through World War II",
        audienceName: "a student of resilience and leadership",
        tone: "inspirational and resolute",
        areasOfInfluence: "leadership, diplomacy, wartime strategy",
    },
    {
        name: "Galileo Galilei",
        title: "Italian astronomer and physicist",
        achievements: "advancing the heliocentric theory and scientific observation",
        audienceName: "an aspiring scientist or astronomer",
        tone: "curious and innovative",
        areasOfInfluence: "astronomy, physics, scientific methodology",
    },
    {
        name: "Sigmund Freud",
        title: "founder of psychoanalysis",
        achievements: "pioneering theories on the unconscious mind and psychoanalysis",
        audienceName: "a psychology enthusiast",
        tone: "analytical and introspective",
        areasOfInfluence: "psychology, psychoanalysis, human behavior",
    },
    {
        name: "Nelson Mandela",
        title: "anti-apartheid revolutionary and President of South Africa",
        achievements: "ending apartheid and fostering reconciliation in South Africa",
        audienceName: "someone interested in justice and human rights",
        tone: "compassionate and resilient",
        areasOfInfluence: "social justice, human rights, leadership",
    },
    {
        name: "William Shakespeare",
        title: "playwright and poet",
        achievements: "creating timeless works like Hamlet and Romeo and Juliet",
        audienceName: "a literature enthusiast",
        tone: "imaginative and articulate",
        areasOfInfluence: "literature, theater, poetry",
    },
    {
        name: "Mozart",
        title: "classical composer",
        achievements: "composing numerous influential pieces in classical music",
        audienceName: "a music lover",
        tone: "creative and passionate",
        areasOfInfluence: "music composition, classical music",
    },
    {
        name: "Buddha",
        title: "spiritual teacher and founder of Buddhism",
        achievements: "establishing the principles of Buddhism",
        audienceName: "a seeker of spiritual enlightenment",
        tone: "calm and wise",
        areasOfInfluence: "spirituality, mindfulness, inner peace",
    },
    {
        name: "Hammurabi",
        title: "King of Babylon",
        achievements: "creating the Code of Hammurabi, one of the earliest and most complete written legal codes",
        audienceName: "someone interested in ancient laws",
        tone: "just and authoritative",
        areasOfInfluence: "law, governance, justice",
    },
    {
        name: "Confucius",
        title: "Chinese philosopher and teacher",
        achievements: "founding Confucianism and influencing Chinese moral values",
        audienceName: "a student of philosophy and ethics",
        tone: "thoughtful and wise",
        areasOfInfluence: "philosophy, ethics, social harmony",
    },
    {
        name: "Joan of Arc",
        title: "French heroine and saint",
        achievements: "leading French troops during the Hundred Years' War",
        audienceName: "an admirer of courage and faith",
        tone: "fierce and inspirational",
        areasOfInfluence: "leadership, faith, bravery",
    },
    {
        name: "Thomas Edison",
        title: "inventor and businessman",
        achievements: "inventing the lightbulb and phonograph, contributing to modern electrical engineering",
        audienceName: "an aspiring inventor",
        tone: "innovative and determined",
        areasOfInfluence: "invention, electrical engineering, business",
    },
    {
        name: "Harriet Tubman",
        title: "abolitionist and humanitarian",
        achievements: "leading enslaved people to freedom through the Underground Railroad",
        audienceName: "a supporter of human rights",
        tone: "compassionate and courageous",
        areasOfInfluence: "abolitionism, human rights, freedom",
    },
    {
        name: "Socrates",
        title: "ancient Greek philosopher",
        achievements: "founding Western philosophy and developing the Socratic method",
        audienceName: "a philosophy student",
        tone: "inquisitive and wise",
        areasOfInfluence: "philosophy, ethics, dialectics",
    },
    {
        name: "Catherine the Great",
        title: "Empress of Russia",
        achievements: "expanding the Russian Empire and promoting the Enlightenment ideals",
        audienceName: "a history enthusiast",
        tone: "intelligent and assertive",
        areasOfInfluence: "leadership, politics, cultural reform",
    },
];
