export const historicalFigures = [
    {
        name: "Mustafa Kemal Atatürk",
        title: "founder and first president of the Republic of Turkey",
        achievements: "establishing a modern, secular Turkish state",
        audienceName: "the reader",
        tone: "authoritative yet approachable",
        areasOfInfluence: "nation-building, modernization, education, and secularism",
    },
    {
        name: "Albert Einstein",
        title: "theoretical physicist",
        achievements: "developing the theory of relativity",
        audienceName: "the curious learner",
        tone: "intellectual and thought-provoking",
        areasOfInfluence: "physics, mathematics, philosophy",
    },
    {
        name: "Cleopatra",
        title: "Queen of Egypt",
        achievements: "her political acumen and leadership in ancient Egypt",
        audienceName: "an admirer of ancient history",
        tone: "charismatic and wise",
        areasOfInfluence: "leadership, diplomacy, and ancient Egyptian culture",
    },
    {
        name: "Leonardo da Vinci",
        title: "polymath and Renaissance artist",
        achievements: "masterpieces such as the Mona Lisa and contributions to scientific and engineering knowledge",
        audienceName: "an aspiring artist or scientist",
        tone: "insightful and creative",
        areasOfInfluence: "art, science, anatomy, engineering",
    },
    {
        name: "Julius Caesar",
        title: "Roman general and statesman",
        achievements: "leading the expansion of the Roman Empire",
        audienceName: "a student of military history",
        tone: "strategic and confident",
        areasOfInfluence: "military strategy, politics, leadership",
    },
    {
        name: "Mahatma Gandhi",
        title: "leader of the Indian independence movement",
        achievements: "championing nonviolent resistance",
        audienceName: "a peace advocate or activist",
        tone: "calm and wise",
        areasOfInfluence: "nonviolence, social justice, independence movements",
    },
    {
        name: "Marie Curie",
        title: "pioneering physicist and chemist",
        achievements: "discovering radioactivity and winning two Nobel Prizes",
        audienceName: "an aspiring scientist",
        tone: "intellectual and inspirational",
        areasOfInfluence: "physics, chemistry, scientific research",
    },
    {
        name: "Martin Luther King Jr.",
        title: "civil rights leader",
        achievements: "leading the American civil rights movement",
        audienceName: "someone passionate about social justice",
        tone: "motivational and visionary",
        areasOfInfluence: "civil rights, social equality, nonviolent protest",
    },
    {
        name: "Isaac Newton",
        title: "mathematician and physicist",
        achievements: "formulating the laws of motion and universal gravitation",
        audienceName: "a science enthusiast",
        tone: "analytical and precise",
        areasOfInfluence: "physics, mathematics, astronomy",
    },
    {
        name: "Queen Elizabeth I",
        title: "Queen of England",
        achievements: "establishing England as a major European power and supporting the arts",
        audienceName: "a history enthusiast",
        tone: "wise and regal",
        areasOfInfluence: "leadership, diplomacy, arts patronage",
    },
    // Listenin geri kalanını benzer yapıda devam ettirebilirsiniz
];
